### ISSUE TITLE
Cannot join Slack

### ISSUE THREAD

**Issue by jackap** [banzaicloud/go-cruise-control#104]
**Describe the bug**
Cannot join Slack. Seems the link has expired

**Screenshots**
<img width="1431" alt="Screenshot 2023-12-15 at 15 35 17" src="https://github.com/banzaicloud/go-cruise-control/assets/17317134/e46db509-a1f8-4f1d-98e9-5c00adb8d0ed">

**Comment by chrisgacsal** [comment]
@jackap Thanks for letting us know about the issue. The link has been fixed. You should be able to join.
